# Generated by Django 5.1.7 on 2025-03-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                (
                    "title_ky",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "description_ru",
                    models.TextField(null=True, verbose_name="Описание"),
                ),
                (
                    "description_ky",
                    models.TextField(null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name_plural": "Услуги",
            },
        ),
    ]
