# Generated by Django 5.1.7 on 2025-03-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(max_length=25, verbose_name="Номер телефона"),
        ),
    ]
