# Generated by Django 5.1.7 on 2025-03-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariffs",
            name="title_ky",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="tariffs",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="tariffs",
            name="type_ky",
            field=models.CharField(max_length=155, null=True, verbose_name="Тип"),
        ),
        migrations.AddField(
            model_name="tariffs",
            name="type_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Тип"),
        ),
    ]
