# Generated by Django 5.1.7 on 2025-03-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_settings_alter_servicestrans_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="about_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка о нас"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="about_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка о нас"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="business_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Бизнес встречи"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="business_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Бизнес встречи"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="contact_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка контактов"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="contact_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка контактов"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="description_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="settings",
            name="description_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="settings",
            name="drivers_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Водители"),
        ),
        migrations.AddField(
            model_name="settings",
            name="drivers_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Водители"),
        ),
        migrations.AddField(
            model_name="settings",
            name="email_en",
            field=models.CharField(max_length=155, null=True, verbose_name="почта"),
        ),
        migrations.AddField(
            model_name="settings",
            name="email_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="почта"),
        ),
        migrations.AddField(
            model_name="settings",
            name="enter_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Введите пункт назначения"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="enter_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Введите пункт назначения"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="event_en",
            field=models.CharField(max_length=155, null=True, verbose_name="События"),
        ),
        migrations.AddField(
            model_name="settings",
            name="event_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="События"),
        ),
        migrations.AddField(
            model_name="settings",
            name="info_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Информаций"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="info_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка Информаций"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="location_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка локаций"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="location_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка локаций"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="name_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="settings",
            name="name_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="settings",
            name="number_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="number_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="order_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заказ"),
        ),
        migrations.AddField(
            model_name="settings",
            name="order_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заказ"),
        ),
        migrations.AddField(
            model_name="settings",
            name="our_services_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Наши услуги"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="our_services_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Наши услуги"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="phone_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Телефон"),
        ),
        migrations.AddField(
            model_name="settings",
            name="phone_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Телефон"),
        ),
        migrations.AddField(
            model_name="settings",
            name="pick_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Подобрать "
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="pick_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Подобрать "
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="pick_up_date_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Дата получения"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="pick_up_date_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Дата получения"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="review_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка о отзывы"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="review_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка о отзывы"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="send_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Отправить"),
        ),
        migrations.AddField(
            model_name="settings",
            name="send_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Отправить"),
        ),
        migrations.AddField(
            model_name="settings",
            name="services_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка о услуги"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="services_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка о услуги"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="support_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Поддержать"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="support_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Поддержать"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="sviper_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Что говорят наши клиенты"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="sviper_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Что говорят наши клиенты"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="tarif_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка о тариф"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="tarif_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Заголовка о тариф"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="tariff_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Тариф"),
        ),
        migrations.AddField(
            model_name="settings",
            name="tariff_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Тариф"),
        ),
        migrations.AddField(
            model_name="settings",
            name="text_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Текстовые обзоры"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="text_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Текстовые обзоры"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="settings",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="settings",
            name="video_en",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Видеообзоры"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="video_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Видеообзоры"
            ),
        ),
    ]
