# Generated by Django 5.1.7 on 2025-03-17 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_tariffs_title_ky_tariffs_title_ru_tariffs_type_ky_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="base",
            old_name="description_ky",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="base",
            old_name="title_ky",
            new_name="title_en",
        ),
        migrations.RenameField(
            model_name="services",
            old_name="description_ky",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="services",
            old_name="title_ky",
            new_name="title_en",
        ),
        migrations.RenameField(
            model_name="tariffs",
            old_name="title_ky",
            new_name="title_en",
        ),
        migrations.RenameField(
            model_name="tariffs",
            old_name="type_ky",
            new_name="type_en",
        ),
    ]
