# Generated by Django 5.1.7 on 2025-03-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_settings_about_en_settings_about_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="banner_link",
            field=models.URLField(default=1, verbose_name="Ссылка"),
            preserve_default=False,
        ),
    ]
