# Generated by Django 5.1.7 on 2025-03-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_tariffs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "description",
                    models.CharField(max_length=155, verbose_name="Описание"),
                ),
                ("tariff", models.CharField(max_length=155, verbose_name="Тарифы")),
                ("date", models.CharField(max_length=255, verbose_name="Дата")),
                (
                    "phone_number",
                    models.CharField(max_length=155, verbose_name="Номер телефона"),
                ),
            ],
            options={
                "verbose_name_plural": "Обратный связ",
            },
        ),
    ]
