# Generated by Django 5.1.7 on 2025-03-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="base",
            name="links",
            field=models.URLField(blank=True, null=True, verbose_name="Сыылка"),
        ),
    ]
